package d.g.b;

import android.view.ViewGroup.MarginLayoutParams;
import androidx.constraintlayout.widget.ConstraintLayout.a;
import java.util.Arrays;

public class c$a
{
  public int A = -1;
  public int B = -1;
  public int C = -1;
  public int D = -1;
  public int E = -1;
  public int F = -1;
  public int G = -1;
  public int H = -1;
  public int I = -1;
  public int J = 0;
  public int K = -1;
  public int L = -1;
  public int M = -1;
  public int N = -1;
  public int O = -1;
  public int P = -1;
  public float Q = 0.0F;
  public float R = 0.0F;
  public int S = 0;
  public int T = 0;
  public float U = 1.0F;
  public boolean V = false;
  public float W = 0.0F;
  public float X = 0.0F;
  public float Y = 0.0F;
  public float Z = 0.0F;
  public boolean a = false;
  public float a0 = 1.0F;
  public int b;
  public float b0 = 1.0F;
  public int c;
  public float c0 = NaN.0F;
  public int d;
  public float d0 = NaN.0F;
  public int e = -1;
  public float e0 = 0.0F;
  public int f = -1;
  public float f0 = 0.0F;
  public float g = -1.0F;
  public float g0 = 0.0F;
  public int h = -1;
  public boolean h0 = false;
  public int i = -1;
  public boolean i0 = false;
  public int j = -1;
  public int j0 = 0;
  public int k = -1;
  public int k0 = 0;
  public int l = -1;
  public int l0 = -1;
  public int m = -1;
  public int m0 = -1;
  public int n = -1;
  public int n0 = -1;
  public int o = -1;
  public int o0 = -1;
  public int p = -1;
  public float p0 = 1.0F;
  public int q = -1;
  public float q0 = 1.0F;
  public int r = -1;
  public boolean r0 = false;
  public int s = -1;
  public int s0 = -1;
  public int t = -1;
  public int t0 = -1;
  public float u = 0.5F;
  public int[] u0;
  public float v = 0.5F;
  public String v0;
  public String w = null;
  public int x = -1;
  public int y = 0;
  public float z = 0.0F;
  
  public final void a(int paramInt, d.a parama)
  {
    d = paramInt;
    h = d;
    i = e;
    j = f;
    k = g;
    l = h;
    m = i;
    n = j;
    o = k;
    p = l;
    q = p;
    r = q;
    s = r;
    t = s;
    u = z;
    v = A;
    w = B;
    x = m;
    y = n;
    z = o;
    A = P;
    B = Q;
    C = R;
    g = c;
    e = a;
    f = b;
    b = width;
    c = height;
    D = leftMargin;
    E = rightMargin;
    F = topMargin;
    G = bottomMargin;
    Q = E;
    R = D;
    T = G;
    S = F;
    boolean bool = S;
    h0 = bool;
    i0 = T;
    j0 = H;
    k0 = I;
    h0 = bool;
    l0 = L;
    m0 = M;
    n0 = J;
    o0 = K;
    p0 = N;
    q0 = O;
    H = parama.getMarginEnd();
    I = parama.getMarginStart();
    U = m0;
    X = p0;
    Y = q0;
    Z = r0;
    a0 = s0;
    b0 = t0;
    c0 = u0;
    d0 = v0;
    e0 = w0;
    f0 = x0;
    g0 = y0;
    W = o0;
    V = n0;
  }
  
  public void a(ConstraintLayout.a parama)
  {
    d = h;
    e = i;
    f = j;
    g = k;
    h = l;
    i = m;
    j = n;
    k = o;
    l = p;
    p = q;
    q = r;
    r = s;
    s = t;
    leftMargin = D;
    rightMargin = E;
    topMargin = F;
    bottomMargin = G;
    x = P;
    y = O;
    z = u;
    A = v;
    m = x;
    n = y;
    o = z;
    B = w;
    P = A;
    Q = B;
    E = Q;
    D = R;
    G = T;
    F = S;
    S = h0;
    T = i0;
    H = j0;
    I = k0;
    L = l0;
    M = m0;
    J = n0;
    K = o0;
    N = p0;
    O = q0;
    R = C;
    c = g;
    a = e;
    b = f;
    width = b;
    height = c;
    parama.setMarginStart(I);
    parama.setMarginEnd(H);
    parama.a();
  }
  
  public Object clone()
  {
    a locala = new a();
    a = a;
    b = b;
    c = c;
    e = e;
    f = f;
    g = g;
    h = h;
    i = i;
    j = j;
    k = k;
    l = l;
    m = m;
    n = n;
    o = o;
    p = p;
    q = q;
    r = r;
    s = s;
    t = t;
    u = u;
    v = v;
    w = w;
    A = A;
    B = B;
    u = u;
    u = u;
    u = u;
    u = u;
    u = u;
    C = C;
    D = D;
    E = E;
    F = F;
    G = G;
    H = H;
    I = I;
    J = J;
    K = K;
    L = L;
    M = M;
    N = N;
    O = O;
    P = P;
    Q = Q;
    R = R;
    S = S;
    T = T;
    U = U;
    V = V;
    W = W;
    X = X;
    Y = Y;
    Z = Z;
    a0 = a0;
    b0 = b0;
    c0 = c0;
    d0 = d0;
    e0 = e0;
    f0 = f0;
    g0 = g0;
    h0 = h0;
    i0 = i0;
    j0 = j0;
    k0 = k0;
    l0 = l0;
    m0 = m0;
    n0 = n0;
    o0 = o0;
    p0 = p0;
    q0 = q0;
    s0 = s0;
    t0 = t0;
    int[] arrayOfInt = u0;
    if (arrayOfInt != null) {
      u0 = Arrays.copyOf(arrayOfInt, arrayOfInt.length);
    }
    x = x;
    y = y;
    z = z;
    r0 = r0;
    return locala;
  }
}

/* Location:
 * Qualified Name:     d.g.b.c.a
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */