package l.a.b.a.d;

public enum h$b
  implements i
{
  static
  {
    REACTOR_FINAL = new b("REACTOR_FINAL", 2);
    TIMER_TASK = new b("TIMER_TASK", 3);
    CONNECTION_INIT = new b("CONNECTION_INIT", 4);
    CONNECTION_BOUND = new b("CONNECTION_BOUND", 5);
    CONNECTION_UNBOUND = new b("CONNECTION_UNBOUND", 6);
    CONNECTION_LOCAL_OPEN = new b("CONNECTION_LOCAL_OPEN", 7);
    CONNECTION_REMOTE_OPEN = new b("CONNECTION_REMOTE_OPEN", 8);
    CONNECTION_LOCAL_CLOSE = new b("CONNECTION_LOCAL_CLOSE", 9);
    CONNECTION_REMOTE_CLOSE = new b("CONNECTION_REMOTE_CLOSE", 10);
    CONNECTION_FINAL = new b("CONNECTION_FINAL", 11);
    SESSION_INIT = new b("SESSION_INIT", 12);
    SESSION_LOCAL_OPEN = new b("SESSION_LOCAL_OPEN", 13);
    SESSION_REMOTE_OPEN = new b("SESSION_REMOTE_OPEN", 14);
    SESSION_LOCAL_CLOSE = new b("SESSION_LOCAL_CLOSE", 15);
    SESSION_REMOTE_CLOSE = new b("SESSION_REMOTE_CLOSE", 16);
    SESSION_FINAL = new b("SESSION_FINAL", 17);
    LINK_INIT = new b("LINK_INIT", 18);
    LINK_LOCAL_OPEN = new b("LINK_LOCAL_OPEN", 19);
    LINK_REMOTE_OPEN = new b("LINK_REMOTE_OPEN", 20);
    LINK_LOCAL_DETACH = new b("LINK_LOCAL_DETACH", 21);
    LINK_REMOTE_DETACH = new b("LINK_REMOTE_DETACH", 22);
    LINK_LOCAL_CLOSE = new b("LINK_LOCAL_CLOSE", 23);
    LINK_REMOTE_CLOSE = new b("LINK_REMOTE_CLOSE", 24);
    LINK_FLOW = new b("LINK_FLOW", 25);
    LINK_FINAL = new b("LINK_FINAL", 26);
    DELIVERY = new b("DELIVERY", 27);
    TRANSPORT = new b("TRANSPORT", 28);
    TRANSPORT_ERROR = new b("TRANSPORT_ERROR", 29);
    TRANSPORT_HEAD_CLOSED = new b("TRANSPORT_HEAD_CLOSED", 30);
    TRANSPORT_TAIL_CLOSED = new b("TRANSPORT_TAIL_CLOSED", 31);
    TRANSPORT_CLOSED = new b("TRANSPORT_CLOSED", 32);
    SELECTABLE_INIT = new b("SELECTABLE_INIT", 33);
    SELECTABLE_UPDATED = new b("SELECTABLE_UPDATED", 34);
    SELECTABLE_READABLE = new b("SELECTABLE_READABLE", 35);
    SELECTABLE_WRITABLE = new b("SELECTABLE_WRITABLE", 36);
    SELECTABLE_EXPIRED = new b("SELECTABLE_EXPIRED", 37);
    SELECTABLE_ERROR = new b("SELECTABLE_ERROR", 38);
    SELECTABLE_FINAL = new b("SELECTABLE_FINAL", 39);
    a locala = new a("NON_CORE_EVENT", 40);
    NON_CORE_EVENT = locala;
    $VALUES = new b[] { REACTOR_INIT, REACTOR_QUIESCED, REACTOR_FINAL, TIMER_TASK, CONNECTION_INIT, CONNECTION_BOUND, CONNECTION_UNBOUND, CONNECTION_LOCAL_OPEN, CONNECTION_REMOTE_OPEN, CONNECTION_LOCAL_CLOSE, CONNECTION_REMOTE_CLOSE, CONNECTION_FINAL, SESSION_INIT, SESSION_LOCAL_OPEN, SESSION_REMOTE_OPEN, SESSION_LOCAL_CLOSE, SESSION_REMOTE_CLOSE, SESSION_FINAL, LINK_INIT, LINK_LOCAL_OPEN, LINK_REMOTE_OPEN, LINK_LOCAL_DETACH, LINK_REMOTE_DETACH, LINK_LOCAL_CLOSE, LINK_REMOTE_CLOSE, LINK_FLOW, LINK_FINAL, DELIVERY, TRANSPORT, TRANSPORT_ERROR, TRANSPORT_HEAD_CLOSED, TRANSPORT_TAIL_CLOSED, TRANSPORT_CLOSED, SELECTABLE_INIT, SELECTABLE_UPDATED, SELECTABLE_READABLE, SELECTABLE_WRITABLE, SELECTABLE_EXPIRED, SELECTABLE_ERROR, SELECTABLE_FINAL, locala };
  }
  
  public h$b() {}
  
  public boolean isValid()
  {
    return true;
  }
  
  public static enum a
  {
    public a()
    {
      super(paramInt, null);
    }
    
    public boolean isValid()
    {
      return false;
    }
  }
}

/* Location:
 * Qualified Name:     l.a.b.a.d.h.b
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */